#Official JDK8 Alpine-based image
FROM java:openjdk-8-alpine
ADD target/retoIBM-0.0.1-SNAPSHOT.jar /opt/retoIBM-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/opt/retoIBM-0.0.1-SNAPSHOT.jar"]